# Generated by Django 6.0 on 2026-03-28 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('itemprice', models.IntegerField()),
                ('itemdesc', models.TextField()),
                ('itemimage', models.ImageField(upload_to='items/')),
                ('itemcategory', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurant')),
            ],
        ),
    ]
