# Generated by Django 6.0 on 2026-03-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
