# Generated by Django 6.0 on 2026-04-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('rezorpay', models.CharField(blank=True, max_length=100)),
                ('patment_s', models.BooleanField(default=True)),
            ],
        ),
    ]
