# Generated by Django 6.0 on 2026-04-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='patment_s',
        ),
        migrations.AddField(
            model_name='order',
            name='patment_status',
            field=models.BooleanField(default=False),
        ),
    ]
